############# English navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "Orthopédie"
url = "/orthopedie"
weight = 2

[[main]]
name = "Vente et location de matériel médical"
url = "/vente_et_location"
weight = 3

[[main]]
name = "Photos"
url = "/photos"
weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "À propos du fondateur"
url = "/about"
weight = 1

[[footer]]
name = "Mentions légales "
url = "/mentions-legales "
weight = 2




